DROP TABLE IF EXISTS STUDENTS;
DROP TABLE IF EXISTS COURSES;
DROP TABLE IF EXISTS MARKS;


CREATE TABLE STUDENTS
(
    id         INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name  VARCHAR(255) NOT NULL,
    email      VARCHAR(255) NOT NULL
);

CREATE TABLE COURSES
(
    id   INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE GRADES
(
    id         INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    student_id INTEGER    NOT NULL,
    course_id  INTEGER    NOT NULL,
    grade       VARCHAR(1) NOT NULL,
    date       DATE       NOT NULL,
    CONSTRAINT fk_student FOREIGN KEY (student_id) REFERENCES STUDENTS (id),
    CONSTRAINT fk_course FOREIGN KEY (course_id) REFERENCES COURSES (id)
);


